### ISSUE TITLE
Volume monitoring and averange last 10 data

### ISSUE THREAD

**Issue by eliafino** [H3Cki/PumpDetector#3]
Jestem Elia, Miło mi!

Is possible to monitor the volume? I am interested in collecting the last 10 data of the volume, making an average and checking if the last data is above the average by at least 7.7 times and if the last price is higher than the penultimate.
For now I have a working script in bash, but it's not optimized. Your python code is much more functional. But I am ignorant in python.
Can you help me?

Dzięki wielkie,
Elia

**Comment by H3Cki** [comment]
Yo, it is possible for sure, although I am not invested into that project
anymore. I am rather planning to create a new version that has a web app.

**Comment by H3Cki** [comment]
I believe you can experiment with changing functions like `getTickChange()`
and `getLUTickchange()` to work on volume instead of current price (['c']).
But to switch to monitoring volume in the entire script, you would have to
change the display methods to show volume instead of current price etc.
