### ISSUE TITLE
Max reconnect retries reached

### ISSUE THREAD

**Issue by kotik1998** [H3Cki/PumpDetector#4]
![image](https://user-images.githubusercontent.com/23015769/118848604-d0243000-b8c6-11eb-9daf-01fb61f997e6.png)

settings:
{"shortInterval": "1", "longInterval": "15", "minPrice": 1e-06, "maxShortIncrease": 999.0, "maxLongTolerance": 1.0, "jumpThresholds": [0.0, 2.0, 2.5], "minSellPercentage": 1.0, "maxLossPercentage": -1.0, "minTrades": 0, "stageForListing": 1, "printLimit": 10, "topXHighlighted": 3, "minPrintInterval": 1.0, "minSecondaryPrintInterval": 1.0, "simpleValues": false, "simpleValuesFormating": false, "waitForNewKline": false, "maxKlineTime": 60, "skipMenu": false}

**Comment by kotik1998** [comment]
whats wrong with the program?

**Comment by kotik1998** [comment]
And how can i add my binance account for this to auto buy and sell?

**Comment by H3Cki** [comment]
Hi, this script may be outdated, I don't recommend using it since it hasn't
been updated in a long time. I'm no longer invested in that project so all
fixes are on you.
